### ISSUE TITLE
Brainstorm poster contents in this issue

### ISSUE THREAD

**Issue by oneSIX** [TeamGFS/GFSClock#110]
This is associated with the [Poster_Documentation](https://github.com/TeamGFS/GFSClock/tree/Poster_Documentation) branch.

Bikes.

**Comment by peterse2** [comment]
Three main topics to cover 1. Purpose of Project/Initial Problem 2. Approach/Framework used 3. Later features

**Comment by seitensei** [comment]
1. Cost Savings, Hardware Cost/Replacement
2. Android/RetroFit
3. Things
