### ISSUE TITLE
Determine if badge/barcode corresponds to an actual employee

### ISSUE THREAD

**Issue by oneSIX** [TeamGFS/GFSClock#16]

**Comment by seitensei** [comment]
I'm pushing this to Sprint 3, since some more clarification on how to handle alternative forms of input (and associated data aberrations) requires further discussion with GFS.

**Comment by oneSIX** [comment]
This is another of the asynchronous tasks that will need to be written and called from the ClockOptions activity onCreate method.

**Comment by oneSIX** [comment]
This is currently working as of today. (not precisely needed as non-employee's won't be using the timeclock).
