### ISSUE TITLE
API Functionality

### ISSUE THREAD

**Issue by seitensei** [TeamGFS/GFSClock#2]
On the API side, we will be implementing API Mappers for each platform we support, with an API mockup server that we can use to test them against.

For online API access, #67 should be completed.

**Comment by oneSIX** [comment]
Thahn has emailed GFS for a response about this.

**Comment by peterse2** [comment]
- [ ] Determine how to handle fallback

**Comment by seitensei** [comment]
GFS has replied with API documentation. The routes are pretty clear, but now we need to figure out what data and data format that we should be ending and what we except to receive.

**Comment by seitensei** [comment]
Moving this to Sprint 2, so we can discuss more with GFS about the API.

**Comment by seitensei** [comment]
Added #67 to this one.

**Comment by seitensei** [comment]
Going to close off this issue, since everything will be tightly coupled with the APIMapper, for both online and offline.
