### ISSUE TITLE
SCM Preference

### ISSUE THREAD

**Issue by seitensei** [TeamGFS/GFSClock#24]
We have to contact GFS again and figure out what they prefer that we do for source code management (SCM). I know they have their own github organization, but everything within it looks to be private.

**Comment by oneSIX** [comment]
I am going to email Ron and ask about the privacy of the repository, as well as share the Prospectus document.

**Comment by oneSIX** [comment]
response did not include SCM preference.  will IM to inquire.

**Comment by oneSIX** [comment]
going to pseudo close this for now, if we have any private info in the project we will keep that in the build process / environment variables.
