### ISSUE TITLE
GFS API Documentation

### ISSUE THREAD

**Issue by seitensei** [TeamGFS/GFSClock#25]
To mock GFS' API, we actually need to have the documentation on it, in lieu of a working version that we can experiment with it. This will mainly be the endpoints/routes, and the JSON data that is to be received or sent.

**Comment by oneSIX** [comment]
clarification needed about endpoints, initial files relating to cybershift common and server side .java files in shared google drive.

**Comment by seitensei** [comment]
Emailed GFS about getting JSON body for API calls

**Comment by seitensei** [comment]
Pushing this to sprint2, since we forgot to push it.

**Comment by oneSIX** [comment]
This is complete as of our previous meeting with GFS (hangouts video chat).[API-Docs](https://github.com/TeamGFS/GFSClock/wiki/API-Docs)
