### ISSUE TITLE
Persistent Configuration Storage

### ISSUE THREAD

**Issue by seitensei** [TeamGFS/GFSClock#65]
To implement #67, we want to be able to store configuration data persistently and in a secure manner. #66 will hook into this and provide access to the configuration storage from other parts of the application, like the UI and the API Mapper.

Storage should be persistent, and should be retained between application launches. Ideally, this should be some sort of key-value store, so that we can reuse it later on for setting storage as well.

Refer to this link when you're working on this: https://developer.android.com/guide/topics/data/data-storage.html Make sure you update this issue with the storage method you're using.

https://guides.codepath.com/android/Persisting-Data-to-the-Device
https://guides.codepath.com/android/Storing-and-Accessing-SharedPreferences

**Comment by peterse2** [comment]
Using Shared Preferences as long as all the data that needs to be stored is primitive.

**Comment by peterse2** [comment]
https://developer.android.com/reference/android/preference/PreferenceActivity.html

**Comment by peterse2** [comment]
http://www.journaldev.com/9412/android-shared-preferences-example-tutorial

**Comment by oneSIX** [comment]
@peterse2  push your changes please.

**Comment by seitensei** [comment]
@oneSIX @peterse2 Only if it works/bug minimal

**Comment by peterse2** [comment]
Get Shared preferences:
    SharedPreferences pref =   
    PreferenceManager.getDefaultSharedPreferences(this);
    String username = pref.getString("username", "n/a"); 

Set Shared preferences:
SharedPreferences pref =   
    PreferenceManager.getDefaultSharedPreferences(this);
    Editor edit = pref.edit();
    edit.putString("username", "billy");
    edit.putString("user_id", "65");
    edit.commit();
