### ISSUE TITLE
Introduce PIN Activity which protects the Admin panel from access by unauthorized users

### ISSUE THREAD

**Issue by seitensei** [TeamGFS/GFSClock#68]
Associated with #67. 

For this stage, we want to link/glue the UI created in #48 to the functionality that will be implemented for #67.

**Comment by oneSIX** [comment]
I've been looking into this a bit, it seems we may need to change the activity to a SharedPreference object rather than a View object. 
https://developer.android.com/guide/topics/data/data-storage.html

**Comment by oneSIX** [comment]
Formerly titled "Link/Associate UI with Configuration Access" as that is handled by a separate issue [#67](https://github.com/TeamGFS/GFSClock/issues/67) which is complete awaiting PR approval.

I am creating  new branch which will contain the Pin activity.
