### ISSUE TITLE
Sort Punch Cache by Time and Punch Type

### ISSUE THREAD

**Issue by seitensei** [TeamGFS/GFSClock#73]
In order to properly submit punches upstream to the API, we have to sort the punches in our Realm cache in order. 

Generally speaking, sorting it by the time the punch was made (with earlier times first) should be sufficient, but we will have to likely enforce ordering by punch type, since the API will fail in some instances (like punching out before punching in, or punching out for break before punching in for the day).

**Comment by seitensei** [comment]
Might not need to do this, depending on how we empty the cache.

**Comment by oneSIX** [comment]
not needed as all punches can be handled in any order on GFS end.
