### ISSUE TITLE
RetroFit Basic Authentication

### ISSUE THREAD

**Issue by seitensei** [TeamGFS/GFSClock#74]
In order to access the API, we will need to set up RetroFit to handle connections using Basic Authentication. Refer to [this link](https://futurestud.io/tutorials/android-basic-authentication-with-retrofit) for a tutorial.

This one is blocked by #67, which will store the API url and basic auth username and password.

**Comment by agCepeda** [comment]
Hi. I want to help you!

**Comment by seitensei** [comment]
@agCepeda Thanks for inquiring. At this time, we're not looking for help from outside of the organization; sorry if the 'help wanted' tag was misleading. There are quite a few projects out there that do require outside help, though, and you might find something you'd be interested in: http://up-for-grabs.net/#/

**Comment by seitensei** [comment]
Ended up doing other work in the branch for this one, but is done.
