### ISSUE TITLE
Special Case Handling Information Needed

### ISSUE THREAD

**Issue by oneSIX** [TeamGFS/GFSClock#76]
When an employee forgets to sign in for lunch or break ?
or when an employee forgets to clock out.

**Comment by seitensei** [comment]
REST API connects to a SOAP API on GFS side, so punches need to happen in sequence. A little clarification, for anyone contacting GFS:

We're not sure how this is handled when a special case occurs, where an employee forgets to clock out for the day, and comes back the next day to sign in. Or an employee forgets to clock in from a meal or break, and has to clock out at the end of the day.

**Comment by oneSIX** [comment]
Asking GFS / James about this today on Hangouts call.

**Comment by oneSIX** [comment]
Basically this is handled on the server side / upstream. When an employee goes to clock in after a missed clockout action, there may be issues but they will be handled by the server. Offline punches will need to be cached as usual.

**Comment by seitensei** [comment]
No validation of submissions required from our end.
