### ISSUE TITLE
UI Updates, Round 2

### ISSUE THREAD

**Issue by seitensei** [TeamGFS/GFSClock#77]
UI has been greatly improved with @oneSIX's implementation of constrait layouts, but it could be better. 

Going to post the screens, and then talk about layouts. I won't be creating a flow/epic from this, but you're welcome to.

![pasted image at 2017_03_02 02_17 pm](https://cloud.githubusercontent.com/assets/908739/23536500/53332100-ff93-11e6-9987-9e632433c760.png)

Starting with this screen. We certainly have more room to center the controls, and then stretch them out a little more on the tablet sized view. We **don't** want everything aligned to one side.

---

![pasted image at 2017_03_02 02_18 pm](https://cloud.githubusercontent.com/assets/908739/23536524/805276c2-ff93-11e6-8b15-178ebe04d393.png)

For this screen, we want either larger buttons in the tablet view to take up more space. Assume BIG FINGERS. Another alternative is to size up the buttons a little big, and cluster them in two sections: The IN/OUT on the left, and the History/Change/modifiers on the right.

---

![pasted image at 2017_03_02 02_19 pm](https://cloud.githubusercontent.com/assets/908739/23536564/bfae1506-ff93-11e6-8f59-7b69f4d32fbf.png)

No major concerns here that aren't already staged to be taken care of. Something to consider maybe, is to allow for manual entry of employee ID? Needs talking with GFS- and can certainly be rolled into the next sprint.

---
All screenshots created by the super biker @oneSIX &copy; 2017

**Comment by oneSIX** [comment]
this has been linked to another issue (71) closing it after approval of PR.
